[package]
name = "rust-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = "1.0.152"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.26"
